/**
 * Daily digest — a scheduled morning document generated by the default model:
 * yesterday's captures distilled + review outlook + one action suggestion.
 *
 * Runs on the feed alarm (every ~30min); the config gates it (enabled + hour)
 * and kvMeta remembers the last run date so it fires once per day.
 */
import dayjs from 'dayjs'
import type { AIProvider } from '@/services/ai/types'
import { createProvider } from '@/services/ai/factory'
import { DocumentRepository } from '@/db/repositories/document.repository'
import { ModelRepository } from '@/db/repositories/model.repository'
import { MetaRepository } from '@/db/repositories/meta.repository'
import { FlashcardRepository } from '@/db/repositories/flashcard.repository'
import { computeReviewStats, type ReviewLog } from '@/utils/review-stats'
import { dateKey } from '@/utils/date'
import type { DocumentEntity } from '@/types/document'

export interface DigestConfig {
  enabled: boolean
  /** Hour of day (0-23) after which the digest may run. Default 8. */
  hour: number
}

export const DEFAULT_DIGEST_CONFIG: DigestConfig = { enabled: false, hour: 8 }

const CONFIG_KEY = 'daily-digest-config'
const STATE_KEY = 'daily-digest-state'

const DIGEST_PROMPT = `你是用户的个人知识助理，负责生成每日晨报。根据提供的材料输出一份 Markdown 晨报：

## 昨日剪藏
（每篇一句话要点；没有剪藏就写"昨天没有新剪藏"）

## 复习看板
（到期卡片数、连续打卡天数；用一两句话）

## 今日建议
（基于材料给一条具体可执行的建议）

要求：简洁，全文不超过 250 字，用材料中的事实，不要编造。`

export interface DigestMaterialInput {
  docs: Array<Pick<DocumentEntity, 'title' | 'siteName' | 'excerpt' | 'capturedAt'>>
  dueCount: number
  streak: number
  reviewedTotal: number
}

/** Build the material block for the model (pure — for tests). */
export function buildDigestMaterial(input: DigestMaterialInput): string {
  const lines: string[] = []

  const docs = input.docs
    .slice(-20)
    .map((d) => `- 《${d.title || '无标题'}》${d.siteName ? `（${d.siteName}）` : ''}${d.excerpt ? `：${d.excerpt.slice(0, 80)}` : ''}`)
  lines.push(`最近 36 小时剪藏了 ${input.docs.length} 篇文档：`)
  lines.push(docs.length > 0 ? docs.join('\n') : '- （无）')

  lines.push('')
  lines.push(`复习情况：当前到期卡片 ${input.dueCount} 张；连续打卡 ${input.streak} 天；累计复习 ${input.reviewedTotal} 张。`)

  return lines.join('\n')
}

/** Build the digest document entity from the model's markdown (pure). */
export function buildDigestDocument(markdown: string, day: string): Pick<DocumentEntity, 'id' | 'url' | 'title' | 'markdown' | 'tags' | 'extractionMethod' | 'source' | 'capturedAt' | 'updatedAt'> & { contentHash: string } {
  const now = dayjs().toISOString()
  const title = `每日简报 · ${day}`
  const full = `# ${title}\n\n${markdown.trim()}`
  // Stable per-day id: regenerating the same day replaces the previous digest.
  const id = `digest-${day}`
  return {
    id,
    url: `digest://${day}`,
    title,
    markdown: full,
    tags: ['digest'],
    extractionMethod: 'manual',
    source: 'library',
    contentHash: id,
    capturedAt: now,
    updatedAt: now,
  }
}

export interface DigestRunResult {
  ran: boolean
  reason?: string
  documentId?: string
}

/**
 * Fire the digest when due: config enabled, past the configured hour, and not
 * already run today. Best-effort — never throws.
 */
export async function maybeRunDailyDigest(now: Date = new Date()): Promise<DigestRunResult> {
  try {
    const config = { ...DEFAULT_DIGEST_CONFIG, ...((await MetaRepository.get<DigestConfig>(CONFIG_KEY)) ?? {}) }
    if (!config.enabled) return { ran: false, reason: 'disabled' }

    const state = (await MetaRepository.get<{ lastRunDate?: string }>(STATE_KEY)) ?? {}
    const today = dateKey(now)
    if (state.lastRunDate === today) return { ran: false, reason: 'already-ran' }

    if (now.getHours() < config.hour) return { ran: false, reason: 'before-hour' }

    const model = await ModelRepository.findDefault()
    if (!model) return { ran: false, reason: 'no-model' }

    // Material: captures in the last 36h + review outlook.
    const since = dayjs(now).subtract(36, 'hour').toISOString()
    const all = await DocumentRepository.findAll()
    const recent = all.filter((d) => d.capturedAt && d.capturedAt >= since && !d.tags?.includes('digest'))

    const dueCount = await FlashcardRepository.countDue(dayjs(now).toISOString())
    const reviewLog = (await MetaRepository.get<ReviewLog>('review-log')) ?? {}
    const stats = computeReviewStats(reviewLog, now)

    const material = buildDigestMaterial({
      docs: recent,
      dueCount,
      streak: stats.streak,
      reviewedTotal: stats.total,
    })

    const provider: AIProvider = createProvider(model)
    const output = await provider.chat({
      model,
      systemPrompt: DIGEST_PROMPT,
      messages: [{ role: 'user', content: material }],
    })
    if (!output.content.trim()) return { ran: false, reason: 'empty-output' }

    const { DocumentRepository: repo } = await import('@/db/repositories/document.repository')
    const doc = buildDigestDocument(output.content, today)
    await repo.save(doc as any)

    await MetaRepository.set(STATE_KEY, { lastRunDate: today, updatedAt: dayjs(now).toISOString() })
    return { ran: true, documentId: doc.id }
  } catch (e: any) {
    return { ran: false, reason: e?.message || 'error' }
  }
}

export async function saveDigestConfig(config: DigestConfig): Promise<void> {
  await MetaRepository.set(CONFIG_KEY, config)
}

export async function loadDigestConfig(): Promise<DigestConfig> {
  return { ...DEFAULT_DIGEST_CONFIG, ...((await MetaRepository.get<DigestConfig>(CONFIG_KEY)) ?? {}) }
}
