export { default as BaseButton } from './BaseButton.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BaseTextarea } from './BaseTextarea.vue'
export { default as BaseDialog } from './BaseDialog.vue'
export { default as BaseSwitch } from './BaseSwitch.vue'
export { default as BaseTabs } from './BaseTabs.vue'
